# Generated by Django 4.1.7 on 2023-09-04 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0002_сhannel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сhannel',
            new_name='HostingСhannel',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
