# Generated by Django 4.1.7 on 2023-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_video_chanel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='chanel',
            new_name='channel',
        ),
    ]
