# Generated by Django 4.1.7 on 2023-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0005_rename_chanel_video_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingсhannel',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
    ]
