# Generated by Django 4.1.7 on 2023-09-11 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0006_hostingсhannel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingсhannel',
            name='saved_channel',
            field=models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
