# Generated by Django 4.1.7 on 2023-09-13 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0008_video_dislikes_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='saved_video',
            field=models.ManyToManyField(related_name='saved_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostingсhannel',
            name='saved_channel',
            field=models.ManyToManyField(related_name='saved_channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
