# Generated by Django 4.1.7 on 2023-09-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0018_alter_commentparent_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentparent',
            name='parent',
        ),
    ]
