# Generated by Django 4.1.7 on 2023-09-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0019_remove_commentparent_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentparent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.comment'),
        ),
    ]
