# Generated by Django 4.1.7 on 2023-09-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0020_commentparent_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentparent',
            old_name='body',
            new_name='text',
        ),
    ]
