# Generated by Django 4.1.7 on 2023-09-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0021_rename_body_commentparent_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentparent',
            name='com_dislikes_parent',
        ),
        migrations.RemoveField(
            model_name='commentparent',
            name='com_likes_parent',
        ),
    ]
