# Generated by Django 4.1.7 on 2023-09-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0022_remove_commentparent_com_dislikes_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentparent',
            name='self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.commentparent'),
        ),
    ]
