# Generated by Django 4.1.7 on 2023-10-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_hosting', '0023_commentparent_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAboutThePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('violation', models.CharField(choices=[('Контент сексуального характера', 'Контент сексуального характера'), ('Жестокие или отталкивающие сцены', 'Жестокие или отталкивающие сцены'), ('Оскорбления или проявления нетерпимости', 'Оскорбления или проявления нетерпимости'), ('Домогательства или издевательства', 'Домогательства или издевательства'), ('Вредные или опасные действия', 'Вредные или опасные действия'), ('Ложная информация', 'Ложная информация'), ('Жестокое обращение с детьми', 'Жестокое обращение с детьми'), ('Пропаганда терроризма', 'Пропаганда терроризма'), ('Спам или ложная информация', 'Спам или ложная информация'), ('Нарушение законодательства', 'Нарушение законодательства')], max_length=255, null=True)),
                ('text_violation', models.TextField()),
                ('self', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.complaintaboutthepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
