# Generated by Django 4.1.7 on 2023-10-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0024_complaintaboutthepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintaboutthepost',
            name='self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.video'),
        ),
    ]
