# Generated by Django 4.1.7 on 2023-10-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0025_alter_complaintaboutthepost_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintaboutthepost',
            old_name='self',
            new_name='self_video',
        ),
        migrations.AddField(
            model_name='complaintaboutthepost',
            name='self_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.comment'),
        ),
        migrations.AddField(
            model_name='complaintaboutthepost',
            name='self_comment_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_hosting.commentparent'),
        ),
    ]
