# Generated by Django 4.1.7 on 2023-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0026_rename_self_complaintaboutthepost_self_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingсhannel',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
