# Generated by Django 4.1.7 on 2023-10-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0027_hostingсhannel_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingсhannel',
            name='strike',
            field=models.IntegerField(default=0),
        ),
    ]
