# Generated by Django 4.1.7 on 2023-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='strike',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True),
        ),
    ]
