# Generated by Django 4.1.7 on 2023-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersprofile_blocked_usersprofile_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='strike',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True),
        ),
    ]
