# Generated by Django 4.1.7 on 2023-10-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersprofile_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='strike',
            field=models.IntegerField(default=0),
        ),
    ]
